### Get All Item Types
GET http://localhost:5000/api/v2/ItemType

### Get Item Type by ID
GET http://localhost:5000/api/v2/ItemType/1

### Add New Item Type
POST http://localhost:5000/api/v2/ItemType
Content-Type: application/json

{
    "name": "M.1",
    "description": "A category for items related to personal hygiene and care products."
}

### Update Existing Item Type
PUT http://localhost:5000/api/v2/ItemType/4
Content-Type: application/json

{
    "name": "Updated Edxternal Hard Drive",
    "description": "",
}


### Delete Item Type
DELETE http://localhost:5000/api/v2/ItemType/1
