### GET all Orders
GET http://localhost:5000/api/v2/orders

###

### GET a specific Order by ID
GET http://localhost:5000/api/v2/orders/1

###

### Create a new Order
POST http://localhost:5000/api/v2/orders
Content-Type: application/json

    {
        "sourceId": 1,
        "orderDate": "2019-04-03T11:33:15Z",
        "requestDate": "2019-04-07T11:33:15Z",
        "reference": "ORD00001",
        "ReferenceExtra": "Bedreven arm straffen bureau.",
        "OrderStatus": "Delivered",
        "notes": "Voedsel vijf vork heel.",
        "ShippingNotes": "Buurman betalen plaats bewolkt.",
        "PickingNotes": "Ademen fijn volgorde scherp aardappel op leren.",
        "warehouseId": 18,
        "ShipTo": 1,
        "BillTo": 1,
        "shipmentId": 1,
        "totalAmount": 9905.13,
        "totalDiscount": 150.77,
        "totalTax": 372.72,
        "totalSurcharge": 77.6,
        "items": [
            {
                "ItemId": "P000001",
                "amount": 23
            }
        ]
    }

###

### Update an existing Order
PUT http://localhost:5000/api/v2/orders/1
Content-Type: application/json

{
    "id": 1,
    "sourceId": 101,
    "orderDate": "2023-05-01T13:45:00Z",
    "requestDate": "2024-05-05T00:00:00Z",
    "reference": "ORD001",
    "referenceExtra": "First bulk order -- Updated",
    "orderStatus": "Shipped -- Updated",
    "notes": "Please ensure timely delivery. -- Updated",
    "shippingNotes": "Handle with care.-- Updated",
    "pickingNotes": "Verify items before dispatch.-- Updated",
    "warehouseId": 3,
    "shipTo": 1,
    "billTo": 2,
    "shipmentId": 1,
    "totalAmount": 100.00,
    "totalDiscount": 100.00,
    "totalTax": 45.00,
    "totalSurcharge": 30.00,
    "items": [
        {
            "itemId": 1,
            "amount": 50
        }
    ]
}

###

### Delete an Order
DELETE http://localhost:5000/api/v2/orders/1