### Get All Item Types
GET http://localhost:5000/api/v1/ItemType

### Get Item Type by ID
GET http://localhost:5000/api/v1/ItemType/1

### Add New Item Type
POST http://localhost:5000/api/v1/ItemType
Content-Type: application/json

{
    "id": 2,
    "name": "M.2",
    "description": "",
    "created_at": "1970-08-09 15:03:12",
    "updated_at": "1999-12-03 23:36:46"
}

### Update Existing Item Type
PUT http://localhost:5000/api/v1/ItemType/1
Content-Type: application/json

{
    "id": 1,
    "name": "Updated External Hard Drive",
    "description": "",
    "created_at": "1970-08-09 15:03:12",
    "updated_at": "1999-12-03 23:36:46"
}


### Delete Item Type
DELETE http://localhost:5000/api/v1/ItemType/1
