### GET all Transfers
GET http://localhost:5000/api/v1/transfers
Headers:
    X-API-KEY: a1b2c3d4e5

###

### GET a specific Transfer by ID
GET http://localhost:5000/api/v1/transfers/1
Headers:
    X-API-KEY: a1b2c3d4e5

###

### Create a new Transfer
POST http://localhost:5000/api/v1/transfers
Headers:
    X-API-KEY: a1b2c3d4e5
Content-Type: application/json

{
    "reference": "TRANS001",
    "transferFrom": 1,
    "transferTo": 2,
    "transferStatus": "Processed",
    "items": [
        {
            "itemId": 1,
            "amount": 50
        },
        {
            "itemId": 2,
            "amount": 30
        }
    ]
}

###

### Update an existing Transfer
PUT http://localhost:5000/api/v1/transfers/1
Headers:
    X-API-KEY: a1b2c3d4e5
Content-Type: application/json

{
    "id": 1,
    "reference": "TRANS001",
    "transferFrom": 1,
    "transferTo": 2,
    "transferStatus": "Completed --updated",
    "items": [
        {
            "itemId": 1,
            "amount": 50
        },
        {
            "itemId": 2,
            "amount": 30
        }
    ]
}

###

### Delete a Transfer
DELETE http://localhost:5000/api/v1/transfers/1
Headers:
    X-API-KEY: a1b2c3d4e5