name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend-build:
    name: Backend Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Build backend
        run: npm run build

  backend-unit-test-a:
    name: Backend Unit Test A
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Unit Test A
        run: npm run test:a

  backend-unit-test-b:
    name: Backend Unit Test B
    runs-on: ubuntu-latest
    needs: backend-build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run Unit Test B
        run: npm run test:b

  end-to-end-test:
    name: End-to-End Test
    runs-on: ubuntu-latest
    needs: [backend-unit-test-a, backend-unit-test-b]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: Run End-to-End Tests
        run: npm run test:e2e

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: end-to-end-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Staging
        run: npm run deploy:staging

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Deploy to Production
        run: npm run deploy:production